<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>f8bca50a-5e3a-498a-8385-51d5f74ea3bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>${GlobalVariable.xpath_input_password}</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@placeholder='Password']</value>
      <webElementGuid>c84977a4-65af-47f1-85ed-1a730869dd56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@name='password</value>
      <webElementGuid>0e826948-e10b-4941-95e3-d999a9d83dac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
