<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_save_custom_fields</name>
   <tag></tag>
   <elementGuidId>031614df-45b6-4b3d-b999-107ca7813498</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='orangehrm-edit-employee-content']/div[2]/div/form/div[@class='oxd-form-actions']/button[contains(.,'Save')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
