<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_save_personal_details</name>
   <tag></tag>
   <elementGuidId>5ef10f07-7e78-44a9-aeac-d3395d55c234</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='orangehrm-edit-employee-content']/div[1]/form/div[@class='oxd-form-actions']/button[contains(.,'Save')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
